### ISSUE TITLE
broken pods

### ISSUE THREAD

**Issue by gerchicov-bp** [Sahilberi/SwiftyDropDataListing#5]
Created empty project and added it via cocoapods. Result - "Swift compiler error":
```let jsonRequestObj = voidSerializer.serialize()```

```.../Pods/SwiftyDropbox/Source/SwiftyDropbox/Shared/Handwritten/DropboxTransportClient.swift:82:59: Missing argument for parameter #1 in call```

Checked - if I download pure dropbox without your library - it downloads version 4.2.x which is correct. So the problem is in your podspec only

**Comment by gerchicov-bp** [comment]
tried to fix it via pull request - now it shows other errors like "SelectedDropboxData undeclared". According to your sources you didn't include all the necessary files

**Comment by Sahilberi** [comment]
Hi @gerchicov-bp I have updated the pods and it's working fine. please check the latest code. and apologies for late reply.
