### ISSUE TITLE
how can we open the files from dropbox and View:?

### ISSUE THREAD

**Issue by sreejithsree123** [Sahilberi/SwiftyDropDataListing#7]
if i have so many files in dropbox which i want to see the content inside the file then how can i view the file?.Files such as PDF, docx, doc, pub etc.

**Comment by Sahilberi** [comment]
You have to do some changes in DBListingViewController to view files such as pdf, doc etc. 

Hide  these code in didSelectRow 

               self.delegate?.getDropboxSelectedData([url.absoluteString])
               let _ = self.navigationController?.popViewController(animated: true)

And create the instance of FileViewerViewController and push to FileViewerViewController. Also set the  "FileViewerViewController" storyboard for FileViewerViewController in Main storyboard.
   
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let conroller =  storyboard.instantiateViewController(withIdentifier: "FileViewerViewController") as! FileViewerViewController
            conroller.fileUrl = url

            self.navigationController?.pushViewController(conroller, animated: true)
